### ISSUE TITLE
Grids not scrollable in mobile Firefox on Android

### ISSUE THREAD

**Issue by olaf-2** [vaadin/vaadin-crud-flow#113]
The grid is not scrollable in mobile Firefox on Android (v63.0.2), neither in my own application nor in the demos from this repo.

**Comment by alvarezguille** [comment]
Thanks for reporting this, did a bit of research and it seems to be an issue in vaadin-grid that crud uses, I'll close this as a duplicate, please subscribe to https://github.com/vaadin/vaadin-grid/issues/1231 to know more about the issue progress
