### ISSUE TITLE
BinderCrudEditor doesn't update the UI if it's not valid

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-crud-flow#115]
As a developer I want the UI to be updated when user wants to save invalid data

**Comment by alvarezguille** [comment]
By default a save event on a crud with a BinderCrudEditor will check if isValid and return without updating the invalid fields in the UI

Overriding BinderCrudEditor#isValid to do `binder.validate().isOk()` would do the trick, but this could be the default behavior

On one hand it's unexpected for a method named `isValid` that it updates the UI, one option would be modify `CrudEditor` so that there is a validate method that is expected to update the UI if editor is invalid.

**Comment by ssindelar** [comment]
Just encountered the same problem. I think updating the UI should be the default behaviour because now if you hit the save button it happens that it doesn't show an error message but doesn't save either.
