### ISSUE TITLE
Java API: Toolbar Buttons

### ISSUE THREAD

**Issue by anezthes** [vaadin/vaadin-crud-flow#189]
I wish I could change the button texts without having to replace the entire toolbar.

**Comment by alvarezguille** [comment]
@anezthes are you referring to the text in the "new item" button or the "cancel"/"save" buttons in the editor? 
You can change the text for those with the [i18n java API](https://vaadin.com/api/platform/14.1.21/com/vaadin/flow/component/crud/Crud.html#setI18n-com.vaadin.flow.component.crud.CrudI18n-)
Take a look at the [Internationalization  demo](https://vaadin.com/components/vaadin-crud/java-examples)

**Comment by anezthes** [comment]
Awesome, thanks!
