### ISSUE TITLE
Adding a clicklistener to Crud Grid that opens an edit dialog results in the wrong title after new item is used

### ISSUE THREAD

**Issue by vesanieminen** [vaadin/vaadin-crud-flow#190]
Steps to reproduce:

1. Download the [attached project "v14-enhanced-crud-test.zip"](https://github.com/vaadin/vaadin-crud-flow/files/4427733/v14-enhanced-crud-test.zip) and run it with `mvn jetty:run`
2. Navigate to localhost:8080 with the browser
3. Click on any grid row. A dialog opens with the title "Edit item". Click cancel.
4. Click on the new item button. A dialog opens with the title "New item". Click cancel.
5. Click on any grid row again. A dialog opens with the incorrect title "New item".

Expected behaviour: 
A dialog opens with the title "Edit item".

This same behaviour happens with the [Enhanced Crud component](https://vaadin.com/directory/component/enhanced-crud)

Line 58 in MainView.java surfaces the bug:

`crud.getGrid().addItemClickListener(event -> crud.edit(event.getItem(), Crud.EditMode.EXISTING_ITEM));
`

![flaw](https://user-images.githubusercontent.com/108755/78370845-dfb3bd00-75cf-11ea-8ed6-299fd04dc95d.gif)

**Comment by KasparScherrer** [comment]
Hi, I'm experiencing a very similar issue but still a little different. It's so close though that I will not create my own issue but instead add my findings here, as I suspect they have the same cause.

My Problem is that the Delete Button disappears forever, after the user once opens the CrudEditor with a new item (So the way to reproduce is exactly the same as with OP). I also have the issue of the wrong title, like OP. but it is very strange that in the screencapture-gif from OP there always is a delete button? even for new items.. it seems to me both ways are wrong - the delete button should only appear for existing items, should it not?

Here is my minimal, complete code example for reproduction:

```
@Route(value = "Test")
public class TestView extends VerticalLayout {
    public TestView() {
        Grid<Person> crudGrid = new Grid<>(Person.class, true);
        Crud<Person> crud = new Crud<>(Person.class, crudGrid, createPersonEditor());
        crud.setSizeFull();
        crudGrid.addItemClickListener(event -> crud.edit(event.getItem(), Crud.EditMode.EXISTING_ITEM));
        addGridItems(crudGrid);
        add(crud);
    }

    private void addGridItems(Grid<Person> grid) {
        Set<Person> people = new HashSet<>();
        people.add(new Person("John", "Doe"));
        people.add(new Person("Patrick", "Smith"));
        grid.setItems(people);
    }

    private CrudEditor<Person> createPersonEditor() {
        Binder<Person> binder = new Binder<>(Person.class);

        TextField firstName = new TextField("First Name");
        binder.forField(firstName)
                .withNullRepresentation("-")
                .asRequired()
                .bind(Person::getFirstName, Person::setFirstName);

        TextField lastName = new TextField("First Name");
        binder.forField(lastName)
                .withNullRepresentation("-")
                .asRequired()
                .bind(Person::getLastName, Person::setLastName);

        FormLayout formLayout = new FormLayout(firstName, lastName);
        formLayout.setResponsiveSteps(new FormLayout.ResponsiveStep("0", 1));

        return new BinderCrudEditor<>(binder, formLayout);
    }
}
```
![screencapture gif](https://i.imgur.com/H7ltY0z.gif)

**Comment by KasparScherrer** [comment]
Looking at the code `Crud::edit`, it seems that the property `__isNew` is only being set to true if editMode is NEW_ITEM, but is not set to false if editMode is EXISTING_ITEM.

**Comment by DiegoCardoso** [comment]
The fix for this issue is release under the following versions and should land soon on the platform:
- [2.1.2 (V14)](https://github.com/vaadin/vaadin-crud-flow/releases/tag/2.1.2)
- [3.0.1 (V15)](https://github.com/vaadin/vaadin-crud-flow/releases/tag/3.0.1)
- [3.1.0.alpha2 (V16)](https://github.com/vaadin/vaadin-crud-flow/releases/tag/3.1.0.alpha2)
