### ISSUE TITLE
Should be a way to run locally demos without installing vaadin-com

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-crud-flow#52]

**Comment by oluwasayo** [comment]
Fixed by [this commit](https://github.com/vaadin/vaadin-crud-flow/pull/81/files#diff-7e142f8c2a54d2ae2aa30823eb4e720c)

- Change the packaging of the vaadin com demo module from `jar` to `war`
- Run `mvn jetty:run` in the module

**Comment by manolo** [comment]
Is it possible to change the packaging via profile ?
