### ISSUE TITLE
Actions update grid in spite of server-side operation result

### ISSUE THREAD

**Issue by alexberazouski** [vaadin/vaadin-crud-flow#76]
1. Try to delete entry which is protected from being deleted.
CRUD will successfully close the editor and refresh item in grid. However, the item was not updated in DB
2. Same for saving in case of edit-protected items

**Comment by tulioag** [comment]
I'd like to add that any operation can potentially fail due to validations or other reasons, and the CRUD class provides no way to cancel the default action. IMO that seriously limits the applicability in real world scenarios.
